# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
   adapter: postgresql
   encoding: unicode
  
development:
   adapter: postgresql
   encoding: unicode
   host: localhost
   database: library_development
   username: user1
   password: 123456

test:
   adapter: postgresql
   encoding: unicode
   host: localhost
   database: library_test
   username: user1
   password: 123456
 
production:
   adapter: postgresql
   encoding: unicode
   host: localhost
   database: library_production
   username: user1
   password: 123456